### ISSUE TITLE
no-unused-declaration throws an error with React default props

### ISSUE THREAD

**Issue by lukewlms** [cartant/tslint-etc#13]
When I try to run tslint with no-unused-declaration enabled, I get this error:

>The 'no-unused-declaration' rule threw an error in '/src/components/Styles.tsx':
>TypeError: Cannot read property 'getText' of undefined
>   at noUnusedDeclarationRule.js:261:25
>    at Map.forEach (<anonymous>)
>    at Walker.seen
  >  at Walker.seenJsx
 >   at Walker.visitJsxElement
>    at Walker.SyntaxWalker.visitNode
>     at Walker.visitNode
>     at syntaxWalker.js:535:63
>     at visitNode
>     at Object.forEachChild

Here's the component:

```
export const HeaderButton = (props: IHeaderButtonProps) => {
  return (
    <TouchableOpacity
      {...props}
    >
      <RText
        style={{
          color: props.disabled ? "gray" : "black",
          ...props.textStyle,
        }}
      >
        {props.content}
      </RText>
    </TouchableOpacity>
  );
};

HeaderButton.defaultProps = { disabled: false };
```

When I remove the defaultProps line, the linter succeeds so it appears that's where the error is.  (If I disable no-unused-declaration, linting also succeeds.)

I like the look of the library, but looks like it won't be usable for us unless we can resolve this issue.  Thanks for your consideration!

**Comment by cartant** [comment]
This should be fixed in 1.4.2. Thanks for the helpful bug report.
