### ISSUE TITLE
Mysterious version 1.6.0

### ISSUE THREAD

**Issue by bovine3dom** [cartant/tslint-etc#28]
I see there's a version 1.6.0 on NPM but there's no trace of it on this repository. Have you just forgotten to push some code? : )

(Link to issue on our repo for my reference: https://github.com/tridactyl/tridactyl/pull/1747)

**Comment by cartant** [comment]
> Have you just forgotten to push some code?

Yeah. That's almost certainly the case. I'll check in just a bit.

**Comment by cartant** [comment]
Done. Thanks for bringing this to my attention.

**Comment by cartant** [comment]
Hmm. The links in the CHANGELOG are messed up. I'll fix those later. Must have been in a real hurry when I made those changes.
