### ISSUE TITLE
Version 1.6.1 released after 1.7.0

### ISSUE THREAD

**Issue by dmytro-gokun** [cartant/tslint-etc#35]
https://www.npmjs.com/package/tslint-etc

Was it intentional or accidental? Looks like 1.7.0 is not listed in CHANGELOG.md anymore + 1.6.1 is listed as 'latest' in npm. It's confusing.

**Comment by cartant** [comment]
Yeah. It looks like I made this fix - https://github.com/cartant/tslint-etc/issues/34 - locally, without pulling from this repo, and then published it as `1.6.1`. I'll fix this later. Thanks for pointing it out.

**Comment by cartant** [comment]
Should all be sorted now. `1.6.1` should have been published as `1.7.1`. My missing `1.7.0` in the `CHANGELOG` is what messed things up and saw me run the `npm version 1.6.1` command, etc.
