### ISSUE TITLE
Make "no-unused-declaration" support for old way importing modules

### ISSUE THREAD

**Issue by Madejczyk** [cartant/tslint-etc#36]
Hi, I have tried to clean my all unused typescript declaration. I have used configuration from:
https://itnext.io/automatically-remove-all-unused-typescript-imports-in-a-project-afd4eb0e84b7

I have seen that rule "no-unused-declaration" remove only imports with structure:
`import x from "x"`
Can we also support old way of importing? 
import x = require("x")

Do you have idea how can I resolve my issue otherwise?

**Comment by cartant** [comment]
> Can we also support old way of importing?

I would imagine so. If you look at AST explorer, you'll see that there are different AST nodes for each type of import:

https://astexplorer.net/#/gist/f9ea87d6a964c6e4f94e8e7041bb13a5/600ba7b8e0288096c7227af0a0135e87c9abdb8e

You'd need to look at the implementation of the rule and add a visitor for `ImportEqualsDeclaration`. There's a visitor for `ImportDeclaration` here:

https://github.com/cartant/tslint-etc/blob/ddda9a0950006291a964467b0c93cf9b91a32317/source/rules/noUnusedDeclarationRule.ts#L154

Presumably TSLint's `ProgramAwareRuleWalker` - this is an old rule; newer rules don't use a walker - will have a visitor method for that AST node type.

I'd start by adding a tests and would then tweak the rule until it passed. There's a test here that could be extended:

https://github.com/cartant/tslint-etc/blob/ddda9a0950006291a964467b0c93cf9b91a32317/fixtures/no-unused-declaration/unused-imports/fixture.ts.lint

When I'm testing, I change this script to run the specific test:

https://github.com/cartant/tslint-etc/blob/ddda9a0950006291a964467b0c93cf9b91a32317/package.json#L66

Here it would be:

```
"test:debug": "tslint --test fixtures/no-unused-declaration/unused-imports/tslint.json",
```

And then I run it using:

```
yarn test:build && yarn test:debug
```

**Comment by cartant** [comment]
Actually, this seems like a pretty simple change, as `ImportEqualsDeclaration` is only used when there is an identifier to the left of the equals symbol. If destructuring is involved, the node is an `ImportDeclaration` node.

This should be done in https://github.com/cartant/tslint-etc/commit/db44d74a0fa6f2c8430395c5ff8ee261a03a76c5

I'll prep a release.

**Comment by cartant** [comment]
Should work in `1.11.0`. 🤞
