### ISSUE TITLE
[no-assign-mutated-array] Allow assignment to the value returned by splice()

### ISSUE THREAD

**Issue by chrisguttandin** [cartant/tslint-etc#37]
Hi @cartant, as always many thanks for your ongoing effort to create all these useful rules.

I recently enabled the `no-assign-mutated-array` rule in my projects. I noticed that it also prevents assignments to the value returned by `splice()`. What do you think about allowing this to happen? I think it would be okay since in contrast to the other array mutators `splice()` does not return the array itself.

**Comment by cartant** [comment]
Fixed.
