### ISSUE TITLE
no-unused-declaration error on exporting default via inline object

### ISSUE THREAD

**Issue by Hotell** [cartant/tslint-etc#8]
following throws lint error

```ts
function getList<T>(resource: string, urlParams: ResourceUrlParams): Promise<ListResponse<T>> {
// impl
}

export default {
  getList,
}
```

![image](https://user-images.githubusercontent.com/1223799/45038789-44a8d900-b062-11e8-8970-3473e48fbfbc.png)

I know this code looks terrible, It's some of our legacy projects at work which I'm trying to update...

**Comment by cartant** [comment]
This is an easy one. Using `default` sees the `ExportSpecifier` move from the identifier's parent to a grandparent. Will fix this soon.
